import = [
    "~/.config/alacritty/tokyonight_night.toml"
    ]

#[shell]
#program="/bin/zsh"

[window]
opacity=0.8
option_as_alt="OnlyLeft"

[scrolling]
history=20000

[font]
normal={family="GohuFont uni14 Nerd Font Mono", style="Regular"}
offset={x=1, y=0}
size=15

[cursor]
style={shape="Block", blinking="On"}
blink_interval=500
blink_timeout=10
unfocused_hollow=false

[mouse]
hide_when_typing=true
