import = [
    "~/.config/alacritty/tokyonight_night.toml"
    ]

[shell]
program="/bin/zsh"

[window]
opacity=0.95

[scrolling]
history=20000

[font]
normal={family="GohuFont uni14 Nerd Font Mono", style="Regular"}
size=12

[cursor]
style={shape="Block", blinking="On"}
blink_interval=500
blink_timeout=10
unfocused_hollow=false

[mouse]
hide_when_typing=true
