set nocompatible
set termguicolors
set number

set tabstop=4
set softtabstop=4
set shiftwidth=4

set hlsearch
set incsearch
set ignorecase

set noswapfile

set noerrorbells

set laststatus=2

set mouse=a

set ruler

set smartindent

set backspace=2

syntax on
set background=dark
colorscheme one

highlight Comment ctermfg=green
