#! /bin/bash

oldps1="$PS1"

export CLICOLOR=1

export PS1="\[\033[38;5;10m\]\u\[$(tput sgr0)\]: \[$(tput sgr0)\]\[\033[38;5;12m\]\w\[$(tput sgr0)\] \\$ \[$(tput sgr0)\]"

export LSCOLORS=exgxbxdxcxexexabagacad

alias c="clear"
alias ll="ls -l"
alias la="ls -la"
